version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.VisualStudio.ComponentModelHost
    versions:
    - 16.8.239
  - dependency-name: Microsoft.VisualStudio.Threading
    versions:
    - 16.8.55
